/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as DocentesRouteImport } from './routes/docentes'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CarrerasRouteImport } from './routes/carreras'
import { Route as BolsaLaboralRouteImport } from './routes/bolsa-laboral'
import { Route as AdmisionRouteImport } from './routes/admision'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarrerasSlugRouteImport } from './routes/carreras.$slug'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const DocentesRoute = DocentesRouteImport.update({
  id: '/docentes',
  path: '/docentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrerasRoute = CarrerasRouteImport.update({
  id: '/carreras',
  path: '/carreras',
  getParentRoute: () => rootRouteImport,
} as any)
const BolsaLaboralRoute = BolsaLaboralRouteImport.update({
  id: '/bolsa-laboral',
  path: '/bolsa-laboral',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmisionRoute = AdmisionRouteImport.update({
  id: '/admision',
  path: '/admision',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrerasSlugRoute = CarrerasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CarrerasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admision': typeof AdmisionRoute
  '/bolsa-laboral': typeof BolsaLaboralRoute
  '/carreras': typeof CarrerasRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/docentes': typeof DocentesRoute
  '/eventos': typeof EventosRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/nosotros': typeof NosotrosRoute
  '/noticias': typeof NoticiasRoute
  '/portal': typeof PortalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transparencia': typeof TransparenciaRoute
  '/carreras/$slug': typeof CarrerasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admision': typeof AdmisionRoute
  '/bolsa-laboral': typeof BolsaLaboralRoute
  '/carreras': typeof CarrerasRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/docentes': typeof DocentesRoute
  '/eventos': typeof EventosRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/nosotros': typeof NosotrosRoute
  '/noticias': typeof NoticiasRoute
  '/portal': typeof PortalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transparencia': typeof TransparenciaRoute
  '/carreras/$slug': typeof CarrerasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admision': typeof AdmisionRoute
  '/bolsa-laboral': typeof BolsaLaboralRoute
  '/carreras': typeof CarrerasRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/docentes': typeof DocentesRoute
  '/eventos': typeof EventosRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/nosotros': typeof NosotrosRoute
  '/noticias': typeof NoticiasRoute
  '/portal': typeof PortalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transparencia': typeof TransparenciaRoute
  '/carreras/$slug': typeof CarrerasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admision'
    | '/bolsa-laboral'
    | '/carreras'
    | '/contacto'
    | '/docentes'
    | '/eventos'
    | '/faq'
    | '/galeria'
    | '/nosotros'
    | '/noticias'
    | '/portal'
    | '/sitemap.xml'
    | '/transparencia'
    | '/carreras/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admision'
    | '/bolsa-laboral'
    | '/carreras'
    | '/contacto'
    | '/docentes'
    | '/eventos'
    | '/faq'
    | '/galeria'
    | '/nosotros'
    | '/noticias'
    | '/portal'
    | '/sitemap.xml'
    | '/transparencia'
    | '/carreras/$slug'
  id:
    | '__root__'
    | '/'
    | '/admision'
    | '/bolsa-laboral'
    | '/carreras'
    | '/contacto'
    | '/docentes'
    | '/eventos'
    | '/faq'
    | '/galeria'
    | '/nosotros'
    | '/noticias'
    | '/portal'
    | '/sitemap.xml'
    | '/transparencia'
    | '/carreras/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmisionRoute: typeof AdmisionRoute
  BolsaLaboralRoute: typeof BolsaLaboralRoute
  CarrerasRoute: typeof CarrerasRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  DocentesRoute: typeof DocentesRoute
  EventosRoute: typeof EventosRoute
  FaqRoute: typeof FaqRoute
  GaleriaRoute: typeof GaleriaRoute
  NosotrosRoute: typeof NosotrosRoute
  NoticiasRoute: typeof NoticiasRoute
  PortalRoute: typeof PortalRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TransparenciaRoute: typeof TransparenciaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docentes': {
      id: '/docentes'
      path: '/docentes'
      fullPath: '/docentes'
      preLoaderRoute: typeof DocentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreras': {
      id: '/carreras'
      path: '/carreras'
      fullPath: '/carreras'
      preLoaderRoute: typeof CarrerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolsa-laboral': {
      id: '/bolsa-laboral'
      path: '/bolsa-laboral'
      fullPath: '/bolsa-laboral'
      preLoaderRoute: typeof BolsaLaboralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admision': {
      id: '/admision'
      path: '/admision'
      fullPath: '/admision'
      preLoaderRoute: typeof AdmisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreras/$slug': {
      id: '/carreras/$slug'
      path: '/$slug'
      fullPath: '/carreras/$slug'
      preLoaderRoute: typeof CarrerasSlugRouteImport
      parentRoute: typeof CarrerasRoute
    }
  }
}

interface CarrerasRouteChildren {
  CarrerasSlugRoute: typeof CarrerasSlugRoute
}

const CarrerasRouteChildren: CarrerasRouteChildren = {
  CarrerasSlugRoute: CarrerasSlugRoute,
}

const CarrerasRouteWithChildren = CarrerasRoute._addFileChildren(
  CarrerasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmisionRoute: AdmisionRoute,
  BolsaLaboralRoute: BolsaLaboralRoute,
  CarrerasRoute: CarrerasRouteWithChildren,
  ContactoRoute: ContactoRoute,
  DocentesRoute: DocentesRoute,
  EventosRoute: EventosRoute,
  FaqRoute: FaqRoute,
  GaleriaRoute: GaleriaRoute,
  NosotrosRoute: NosotrosRoute,
  NoticiasRoute: NoticiasRoute,
  PortalRoute: PortalRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TransparenciaRoute: TransparenciaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
